<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configuration\**" />
    <Compile Remove="Ventas\**" />
    <EmbeddedResource Remove="Configuration\**" />
    <EmbeddedResource Remove="Ventas\**" />
    <None Remove="Configuration\**" />
    <None Remove="Ventas\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExtreme.AspNet.Data" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
  </ItemGroup>

</Project>
