<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d9a145ed-e245-4d4b-a57f-ee1caeb9d575</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	<NoWarn>1591</NoWarn>
	<AssemblyVersion>1.0.0.16</AssemblyVersion>
	<Title>Nest</Title>
	<Description>Permite utilizar todos los endpoints del sistema NEST.</Description>
	<Copyright>Umbrela Corporation</Copyright>
	<Authors>Gabriel Rodriguez Riveros</Authors>
	<Company>Nest</Company>
	<Product>Nest ERP</Product>
	<Version>$(AssemblyVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" />
    <PackageReference Include="DevExtreme.AspNet.Data" />
    <PackageReference Include="EntityFramework" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
	<PackageReference Include="Microsoft.AspNetCore.OData" />
	<PackageReference Include="HotChocolate.AspNetCore" />
	<PackageReference Include="HotChocolate.Data" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\nest.core.aplicacion.contabilidad\nest.core.aplicacion.contabilidad.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.corporativo\nest.core.aplicacion.corporativo.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.costos\nest.core.aplicacion.costos.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.datasource\nest.core.aplicacion.datasource.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.finanzas\nest.core.aplicacion.finanzas.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.general\nest.core.aplicacion.general.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.iclock\nest.core.aplicacion.iclock.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.legal\nest.core.aplicacion.legal.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.logistica\nest.core.aplicacion.logistica.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.mantto\nest.core.aplicacion.mantto.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.patrimonial\nest.core.aplicacion.patrimonial.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.rrhh\nest.core.aplicacion.rrhh.csproj" />
    <ProjectReference Include="..\nest.core.aplicacion.security\nest.core.aplicacion.security.csproj" />
    <ProjectReference Include="..\nest.core.dominio\nest.core.dominio.csproj" />
    <ProjectReference Include="..\nest.core.driver.postgres\nest.core.driver.postgres.csproj" />
    <ProjectReference Include="..\nest.core.driver.sqlserver\nest.core.driver.sqlserver.csproj" />
    <ProjectReference Include="..\nest.core.infraestructura.db\nest.core.infraestructura.db.csproj" />
  </ItemGroup>

</Project>
