<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\nest.core.aplicacion.utils\nest.core.aplicacion.utils.csproj" />
    <ProjectReference Include="..\nest.core.aplication.auth\nest.core.aplication.auth.csproj" />
    <ProjectReference Include="..\nest.core.dominio\nest.core.dominio.csproj" />
    <ProjectReference Include="..\nest.core.infraestructura.contabilidad\nest.core.infraestructura.contabilidad.csproj" />
    <ProjectReference Include="..\nest.core.infraestructura.security\nest.core.infraestructura.security.csproj" />
  </ItemGroup>
</Project>
